### ISSUE TITLE
Solution code pushed to main branch

### ISSUE THREAD

**Issue by samchappel** [learn-co-curriculum/python-p3-loops#3]
### Canvas Link

https://learning.flatironschool.com/courses/6258/assignments/231345?module_item_id=541450

### Concern

Hi there! It looks like the solution code was pushed to the main branch. When I cloned this lab to complete it, the solution code was already in the looping.py file and all three tests were passing without any updates on my end. Just letting you know!

**Comment by professor-ben** [comment]
Thanks for the update! I'll have this fixed by the end of the day.
