### ISSUE TITLE
Incorrect Instructions

### ISSUE THREAD

**Issue by connork97** [learn-co-curriculum/python-p3-loops#4]
### Canvas Link

https://learning.flatironschool.com/courses/6274/assignments/236172?module_item_id=554041

### Concern

In the "Instructions" section at the bottom of the page on Canvas:

Write a function happy_new_year() using a while loop that outputs numbers starting at 10 and counting down to 1. After reaching 1, print out "Happy New Year!"

Compared to the Github repository's solution code:

def happy_new_year():
    for i in range(10, 0, -1):
        print(i)
    
    print("Happy New Year!")

### Additional Context

I'm not sure if there happens to also be a way to make this work with a while loop, but the instructions clearly state to use the while loop in this lab.   Meanwhile, the solution does not even do that.

### Suggested Changes

Either the instructions need to be changed to reflect what is actually being asked of us, or the solution code should be updated for those who get stuck and look to such a resource for answers/clarifications.  Thanks.

**Comment by professor-ben** [comment]
Just pushed a fix to the solution branch- thanks for contributing to the FIS curriculum!

-Ben

**Comment by connork97** [comment]
Thanks!  I'm sure it will be appreciated.
